# Generated by Django 3.2.7 on 2021-09-14 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=5)),
                ('school_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=1)),
                ('path_target', models.CharField(max_length=20)),
                ('regno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('f_name', models.CharField(blank=True, max_length=40, null=True, verbose_name="Father's Name")),
                ('m_name', models.CharField(blank=True, max_length=40, null=True, verbose_name="Mother's Name")),
                ('g_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('g_name', models.CharField(blank=True, max_length=40, null=True, verbose_name="Guardian's Name")),
                ('sex', models.CharField(max_length=1, verbose_name='Gender')),
                ('religion', models.CharField(max_length=1)),
                ('caste', models.CharField(blank=True, max_length=1, null=True)),
                ('dob', models.CharField(blank=True, max_length=10, null=True, verbose_name='Date of Birth')),
                ('fl', models.CharField(max_length=2, verbose_name='First Language')),
                ('sl', models.CharField(max_length=2, verbose_name='Second Language')),
                ('opt', models.CharField(blank=True, max_length=2, null=True, verbose_name='Optional Elective')),
                ('serial', models.CharField(max_length=4)),
                ('remarks_one', models.CharField(blank=True, max_length=25, null=True)),
                ('remarks_two', models.CharField(blank=True, max_length=25, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school')),
            ],
        ),
    ]
